### ISSUE TITLE
Confused about asyncDerived store not updating on new store values

### ISSUE THREAD

**Issue by Gilgames000** [square/svelte-store#58] opened 2023-04-28 16:34 UTC
Hi! I recently discovered this awesome library and started rewriting my webapp using it as it facilitates async state management a lot. However, I'm having some trouble making the asyncDerived store work correctly.

I have an asyncDerived store that depends on another (synchronous) store which is updated over time. When the sync store is updated I would expect the asyncDerived store to fire off an update, but that's not the case. Here's a code snippet:

```svelte
const blockNumber = writable<bigint | null>(null); /* updated over time by an external module */

const balance = asyncDerived(
    [blockNumber],
    async ([$blockNumber]) => {
        if (!$blockNumber) return; /* needed because blockNumber is first set in the browser context (bigint is not serializable) */
        return await getBalance();
    });
```

The problem is that the load function runs only once (and it won't load the balance even the first time, because blockNumber is initially null). So then I tried to change `asyncDerived` to `derived`, without touching anything else, and surprisingly it works, the store gets updated on every new blockNumber. I thought you couldn't run an async function in this case?

The problem with a regular derived store is that I cannot reload it at will (unless I create a dummy store as a dependency and update it to force a refresh). But in the case of the `asyncDerived` store shown above, if I set `reloadable: true` and do the following, the store actually gets updated on new blockNumber values:

```svelte
if (browser} {
        blockNumber.subscribe(async () => {
        await balance.reload?.();
    });
}
```

Although, in this case, the first good value for the `balance` store will only get loaded after the first new blockNumber value.

Any insights on what I'm doing wrong with the async store?

**Comment by Akolyte01** [comment] 2023-05-02 22:02
The main advantages you would get from an asyncDerived store are the ability to delay running of the asynchronous code until all of the prerequisites have finished loading, access to a promise (via load) that will only resolve after this asynchronous  functionality has completed, and as you pointed out the ability to reload. 

Based on the code you have provided you should not need to reload in that manner. The balance store should run its asynchronous behavior again when blockNumber updates. I'm not sure why it is not in your case just from the information you have provided. Are you able to reproduce the issue in a codesandbox or equivalent? If I were to guess, however, I would suggest checking to make sure that you have maintained an active subscription to 'balance'. If balance has no subscribers then it will not update when blockNumber does. 

For example, if you have a component like this:

```
{#await balance.load() then myBalance}
  <p>{myBalance}</p>
{/await} 
```

Then you only have a subscription to balance during its initial load. After that there is no active subscription and balance will not update. 

Another guess would be that you are encountering some order of operations problem due to the fact that your balance store does not directly use the blockNumber (at least in your snippet). If blockNumber updates and you have an active subscription to balance, then `getBalance()` should run. But you have no guarantee built into the store that you'll actually be operating on new data at that point. That would need to be managed somehow by getBalance. 

I would suggest refactoring so that getBalance takes in the blockNumber to make sure you have up to date data. Additionally from what it sounds like you should take advantage of the loadable nature of writable stores. A writable store will only load after it is provided a value beyond undefined. You are giving an initial value of 'null' which is causing it to load immediately. However if you did not do this you could do something like this:

```
// stores.ts
const blockNumber = writable(); /* set by external module */

const balance = asyncDerived(blockNumber, async ($blockNumber) => {
  return await getBalance($blockNumber);
}); // async behavior is not run until blockNumber is set for the first time

// YourComponent.svelte

{#await balance.load() then _}
  <p>{$balance}<p>
{/await}
```

In fact with such a setup you could simply write balance as `balance = asyncDerived(blockNumber, getBalance);`

**Comment by Akolyte01** [comment] 2023-06-05 18:23
Closing after not receiving any update

**Closed by Akolyte01** 2023-06-05 18:23 UTC
